### ISSUE TITLE
pickling error

### ISSUE THREAD

**Issue by fantes** [rusty1s/pyg_autoscale#11]
Hi

thank you a lot for this brilliant work, it works like a charm, and is very impressive (a perfect addition to already fantastic torch_geometric pack)

I have an issue that seems far beyond my python competences. When i am trying to use several workers with SubgraphLoader, I get a very interesting error:
``` 
_pickle.PicklingError: Can't pickle <class 'torch_geometric.data.batch.Batch'>: it's not the same object as torch_geometric.data.batch.Batch
```
(made a few google searches, but it did not help) 

my setup is a bit more involved than your examples, I will try to describe it, and hopefully give useful information without too much noise.

I have an outer torch_geometric.loader.DataLoader that read samples from disk
this samples are of the form
`MyGraph(torch_geometric.data.Data)`
and redefine `__cat_dim__` and the constructor

(I did not redefine the collation functions, so I get a Batch out of this)
this outer dataloader has a fixed batch size of 1, as I am scaling up to larger graphs

this samples are passed (one by one as my bs is 1) to a code that split it like in your examples:
```
perm, ptr = metis(d.adj_t, num_parts=num_parts, log=self.debug)                                 
data = permute(d, perm, log=self.debug)                        
```

and then it works like a charm if I do:
```
loader = SubgraphLoader(data, ptr, batch_size=inner_batch_size, shuffle=True) 
```

but I get the above error if i do:
```
loader = SubgraphLoader(data, ptr, batch_size=inner_batch_size, shuffle=True, num_workers=2, persistent_workers=True) 
```

So I am wondering I you have any clue on this, or if you know where I should investigate.

Thanks a lot,  and congratulations again for this piece of work and for the whole torch_geometric pack.

**Comment by fantes** [comment]
ok, it seems a bit more clear

there is some confusion between the Batch i give to SubgraphLoader and the Batch it builds;
if I extract  my outer graph from the batch and give it to SubgraphLoader, it works.

Sorry for the noise, and congrats again for all that great stuff !

**Comment by rusty1s** [comment]
Looks still to be a bug, right? Which PyG version are you using? And do you have a minimal example to reproduce?

**Comment by fantes** [comment]
I was  using  2.0.1, it works out of the box with 2.0.3 ....
 
Thank you a lot again (and again!)
