### ISSUE TITLE
Why `cudaMemcpyDeviceToHost` in `read_async_cuda`?

### ISSUE THREAD

**Issue by yzh119** [rusty1s/pyg_autoscale#19]
Hi @rusty1s , awesome work. I'm reading through the codebase and found you were using `cudaMemcpyDeviceToHost` when copying data from `src` (which resides in CPU) and `dst` (which resides in CUDA):

https://github.com/rusty1s/pyg_autoscale/blob/a17350c04910c95b0486110b70b742b5e3f56de5/csrc/cuda/async_cuda.cu#L74-L76

I wonder is it a typo?

**Comment by rusty1s** [comment]
Yes, this is a typo. Amazingly, it still works 🙈

**Comment by rusty1s** [comment]
This is also already fixed in master, see https://github.com/rusty1s/pyg_autoscale/blob/master/csrc/cuda/async_cuda.cu#L76.

**Comment by yzh119** [comment]
Oh nice! I didn't realize I was browsing outdated code.

Thank you @rusty1s !
